# -- config
baseURL = 'https://georgephung123.github.io/'
locale = 'en-us'
title = "George's Journal"
theme = "diary"
enableGitInfo = true
googleAnalytics = "G-ZWS5JM1KXW"
# -----
[params]
subtitle = "George Phung's Blog"
favicon = "/favicon/favicon.ico"
enableGiscus = true

    [params.giscus]
        data_repo="georgephung123/georgephung123.github.io"
        data_repo_id="R_kgDORrwRCA"
        data_category="Announcements"
        data_category_id="DIC_kwDORrwRCM4C5GrH"
        data_mapping="pathname"
        data_strict="0"
        data_reactions-enabled="1"
        data_emit_metadata="0"
        data_input_position="bottom"
        data_theme="preferred_color_scheme"
        data_lang="en"
        crossorigin="anonymous"

# ---


[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 5

[[menu.main]]
url = "/about"
name = "About"
weight = 4

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1