baseURL = 'https://georgephung123.github.io/'
locale = 'en-us'
title = 'My Blog!'
theme = "diary"

[[menu.main]]
url = "/about"
name = "About"
weight = 4

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1