# -- config
baseURL = 'https://georgephung123.github.io/'
locale = 'en-us'
title = "George's Journal"
theme = "diary"
enableGitInfo = true
googleAnalytics = "G-ZWS5JM1KXW"
# -----
enableGiscus = true

[params.giscus]
    data-repo="georgephung123/georgephung123.github.io"
    data-repo-id="R_kgDORrwRCA"
    data-category="Announcements"
    data-category-id="DIC_kwDORrwRCM4C5GrH"
    data-mapping="pathname"
    data-strict="0"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="bottom"
    data-theme="preferred_color_scheme"
    data-lang="en"
    crossorigin="anonymous"

# ---

[params]
subtitle = "George Phung's Blog"
favicon = "/favicon/favicon.ico"

[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 5

[[menu.main]]
url = "/about"
name = "About"
weight = 4

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1